export const Sort = [
  { name: "relevance", id: "sort" },
  { name: "fastest", id: "sort" },
  { name: "distance", id: "sort" },
];

export const Offer = [
  { name: "Free Offer", id: "offer", value: "free_offer" },
  { name: "Deal", id: "offer", value: "deal_offer" },
  { name: "Voucher", id: "offer", value: "voucher_offer" },
];

export const Cuisines = [
  { name: "All" },
  { name: "Asian" },
  { name: "Bakery" },
  { name: "Bangladeshi" },
  { name: "Beverage" },
  { name: "Biryani" },
  { name: "Breakfast" },
  { name: "Burgers" },
  { name: "Cafe" },
  { name: "Cakes" },
  { name: "Chicken" },
  { name: "Chinese" },
  { name: "Chotpoti & Fuchka" },
  { name: "Curry" },
  { name: "Dessert" },
  { name: "Dumpling" },
  { name: "Fast Food" },
  { name: "Fish" },
  { name: "Fried Chicken" },
  { name: "Haleem" },
  { name: "Ice Cream" },
  { name: "Indian" },
  { name: "Italian" },
  { name: "Japanese" },
  { name: "Jilapi" },
  { name: "Juice Corner" },
  { name: "Kebab" },
  { name: "Khichuri" },
  { name: "Meat" },
  { name: "Mediterranean" },
  { name: "Mexican" },
  { name: "Middle Eastern" },
  { name: "Noodles" },
  { name: "Pasta" },
  { name: "Pizza" },
  { name: "Rice Dishes" },
  { name: "Sandwiches" },
  { name: "Seafood" },
  { name: "Shawarma" },
  { name: "Snacks" },
  { name: "Soups" },
  { name: "Sushi" },
  { name: "Thai" },
  { name: "Turkish" },
  { name: "Western" },
  { name: "Wraps" },
];
